// Generated by json-type-extractor. Do not edit by hand.

declare module "gd.json" {
  export interface LayoutOptions {
    "org.eclipse.elk.nodeLabels.placement": string;
    "org.eclipse.elk.nodeSize.minimum": string;
    "org.eclipse.elk.padding": string;
    "org.eclipse.elk.portConstraints": string;
    "org.eclipse.elk.spacing.labelLabel": string;
    "org.eclipse.elk.spacing.labelNode": string;
  }

  export interface LayoutOptions2 {
    "org.eclipse.elk.nodeLabels.placement": string;
    "org.eclipse.elk.padding": string;
    "org.eclipse.elk.portConstraints": string;
  }

  export interface LayoutOptions3 {
    "org.eclipse.elk.port.borderOffset": string;
    "org.eclipse.elk.port.side": string;
  }

  export interface PortsItem {
    height: number;
    id: string;
    layoutOptions: LayoutOptions3;
    width: number;
  }

  export interface ChildrenItem {
    edges: unknown[];
    height: number;
    id: string;
    labels: unknown[];
    layoutOptions: LayoutOptions | LayoutOptions2;
    ports: PortsItem[];
    width: number;
  }

  export interface EdgesItem {
    id: string;
    sources: string[];
    targets: string[];
  }

  export interface LayoutOptions4 {
    "PyPTO.filePath": string;
    "PyPTO.renderMode": string;
    "PyPTO.showTensor": string;
    "elk.direction": string;
    "org.eclipse.elk.algorithm": string;
    "org.eclipse.elk.layered.nodePlacement.strategy": string;
    "org.eclipse.elk.layered.spacing.nodeNodeBetweenLayers": string;
  }

  export interface ElkLayout {
    children: ChildrenItem[];
    edges: EdgesItem[];
    id: string;
    layoutOptions: LayoutOptions4;
  }

  const value: ElkLayout;
}
